# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(711, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.wifi_status = QtWidgets.QLabel(self.centralwidget)
        self.wifi_status.setObjectName("wifi_status")
        self.horizontalLayout_3.addWidget(self.wifi_status)
        self.label_wifi_symbol = QtWidgets.QLabel(self.centralwidget)
        self.label_wifi_symbol.setObjectName("label_wifi_symbol")
        self.horizontalLayout_3.addWidget(self.label_wifi_symbol)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(438, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(246, 246, 246);\n"
"border-radius:20px;\n"
"border:3px solid #34495e;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chat_scrollArea = QtWidgets.QScrollArea(self.frame)
        self.chat_scrollArea.setStyleSheet("border:initial;\n"
"border: 0px solid;")
        self.chat_scrollArea.setWidgetResizable(True)
        self.chat_scrollArea.setObjectName("chat_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 661, 222))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setMinimumSize(QtCore.QSize(600, 200))
        self.widget.setMaximumSize(QtCore.QSize(600, 200))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_img = QtWidgets.QLabel(self.widget)
        self.label_img.setMaximumSize(QtCore.QSize(50, 50))
        self.label_img.setText("")
        self.label_img.setPixmap(QtGui.QPixmap("1.jpg"))
        self.label_img.setScaledContents(True)
        self.label_img.setObjectName("label_img")
        self.verticalLayout_4.addWidget(self.label_img)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setStyleSheet("background-color: rgba(71,121,214,20);")
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.widget)
        self.chat_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.chat_scrollArea)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 59))
        self.plainTextEdit.setStyleSheet("QPlainTextEdit{\n"
"    border-radius:20px;\n"
"    border:3px solid #2c3e50;\n"
"    background-color: transparent;\n"
"    font: 12pt \"微软雅黑\";\n"
"    padding:5px;\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout.addWidget(self.plainTextEdit)
        self.Confirmation_button = QtWidgets.QPushButton(self.centralwidget)
        self.Confirmation_button.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    font-weight: bold;      /* 字体加粗 */\n"
"    font-size: 30px;        /* 字体大小 (可以修改这里来调整大小) */\n"
"    min-width: 40px;\n"
"    min-height: 40px;\n"
"    max-width: 40px;\n"
"    max-height: 40px;\n"
"    border-radius: 20px;    /* 圆形按钮 */\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #333333;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #222222;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #cccccc;\n"
"    color: #666666;\n"
"}")
        self.Confirmation_button.setObjectName("Confirmation_button")
        self.horizontalLayout.addWidget(self.Confirmation_button)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 711, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.wifi_status.setText(_translate("MainWindow", "检测中..."))
        self.label_wifi_symbol.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "请让上位机网络与esp32处于同一网络！"))
        self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "询问任何问题"))
        self.Confirmation_button.setText(_translate("MainWindow", "↑"))
